CREATE DATABASE SIB
GO

USE SIB
GO

CREATE TABLE tblPersona
(nit VARCHAR(30) PRIMARY KEY NOT NULL,
nombre VARCHAR(100) NOT NULL,
correo VARCHAR(100) NOT NULL,
celular VARCHAR(10) NOT NULL,
perfil INT NOT NULL,
id INT IDENTITY(1,1) NOT NULL)
GO

CREATE TABLE tblUsuario
(usuario VARCHAR(30) PRIMARY KEY NOT NULL,
contrasena VARCHAR(100) NOT NULL,
nit VARCHAR(30) NOT NULL,
activo BIT NOT NULL,
id INT IDENTITY(1,1) NOT NULL)
GO

CREATE TABLE tblPerfil
(perfil INT PRIMARY KEY NOT NULL,
descripcion VARCHAR(100) NOT NULL,
maxCantPrestamo INT NOT NULL,
diasPrestamo INT NOT NULL,
maxCantRenovacion INT NOT NULL,
id INT IDENTITY(1,1) NOT NULL)
GO

CREATE TABLE tblMaterial
(codigo VARCHAR (30) PRIMARY KEY NOT NULL,
nombre VARCHAR (200) NOT NULL,
edicion VARCHAR(10) NOT NULL,
cantidad INT NOT NULL,
idEstado INT NOT NULL,
idAutor INT NOT NULL,
idProductor INT NOT NULL)
GO

CREATE TABLE tblMaterialEstado
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
estado VARCHAR(200) NOT NULL)
GO

CREATE TABLE tblMaterialAutor
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
autor VARCHAR(200) NOT NULL)
GO

CREATE TABLE tblMaterialProductor
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
productor VARCHAR(200) NOT NULL)
GO

CREATE TABLE tblReserva
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
codigoMat VARCHAR(30) NOT NULL,
nit VARCHAR(30) NOT NULL,
idEstado INT NOT NULL,
fechaReserva DATETIME NOT NULL,
fechaRegistro DATETIME NOT NULL)
GO

CREATE TABLE tblReservaEstado
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
descripcion VARCHAR(30) NOT NULL)
GO

CREATE TABLE tblPrestamo
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
codigoMat VARCHAR(30) NOT NULL,
idEstadoMat INT NOT NULL,
nit VARCHAR(30) NOT NULL,
idReserva INT,
fechaPrestamo DATETIME NOT NULL,
fechaDevolucion DATETIME NOT NULL,
fechaRegistro DATETIME NOT NULL)
GO

CREATE TABLE tblDevolucion
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
codigoMat VARCHAR(30) NOT NULL,
idEstadoMatPrestamo INT NOT NULL,
idEstadoMatDevolucion INT NOT NULL,
nit VARCHAR(30) NOT NULL,
idReserva INT,
fechaPrestamo DATE NOT NULL,
fechaDevolucion DATE NOT NULL,
fechaDevolucionReal DATE NOT NULL)
GO

CREATE TABLE tblSancion
(id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
codigoMat VARCHAR(30) NOT NULL,
nit VARCHAR(30) NOT NULL,
idDevolucion INT NOT NULL,
monto MONEY NOT NULL,
notas VARCHAR(300))
GO
