--CREACIÓN DE RELACIONES ENTRE LAS TABLAS------------------------------------------------------
ALTER TABLE tblPersona ADD FOREIGN KEY (perfil) REFERENCES tblPerfil (perfil)
ALTER TABLE tblUsuario ADD FOREIGN KEY (nit) REFERENCES tblPersona (nit)
ALTER TABLE tblReserva ADD FOREIGN KEY (nit) REFERENCES tblPersona (nit)
ALTER TABLE tblPrestamo ADD FOREIGN KEY (nit) REFERENCES tblPersona (nit)
ALTER TABLE tblDevolucion ADD FOREIGN KEY (nit) REFERENCES tblPersona (nit)
ALTER TABLE tblMaterial ADD FOREIGN KEY (idEstado) REFERENCES tblMaterialEstado (id)
ALTER TABLE tblMaterial ADD FOREIGN KEY (idAutor) REFERENCES tblMaterialAutor (id)
ALTER TABLE tblMaterial ADD FOREIGN KEY (idProductor) REFERENCES tblMaterialProductor (id)
ALTER TABLE tblReserva ADD FOREIGN KEY (idEstado) REFERENCES tblReservaEstado (id)
ALTER TABLE tblReserva ADD FOREIGN KEY (codigoMat) REFERENCES tblMaterial (codigo)
ALTER TABLE tblPrestamo ADD FOREIGN KEY (codigoMat) REFERENCES tblMaterial (codigo)
ALTER TABLE tblPrestamo ADD FOREIGN KEY (idEstadoMat) REFERENCES tblMaterialEstado (id)
ALTER TABLE tblPrestamo ADD FOREIGN KEY (idReserva) REFERENCES tblReserva (id)
ALTER TABLE tblDevolucion ADD FOREIGN KEY (codigoMat) REFERENCES tblMaterial (codigo)
ALTER TABLE tblDevolucion ADD FOREIGN KEY (idEstadoMatPrestamo) REFERENCES tblMaterialEstado (id)
ALTER TABLE tblDevolucion ADD FOREIGN KEY (idEstadoMatDevolucion) REFERENCES tblMaterialEstado (id)
ALTER TABLE tblDevolucion ADD FOREIGN KEY (idReserva) REFERENCES tblReserva (id)
ALTER TABLE tblSancion ADD FOREIGN KEY (codigoMat) REFERENCES tblMaterial (codigo)
ALTER TABLE tblSancion ADD FOREIGN KEY (idDevolucion) REFERENCES tblDevolucion (id)
ALTER TABLE tblSancion ADD FOREIGN KEY (nit) REFERENCES tblPersona (nit)
GO
